FROM shl198/vep_loftee:97.4_gnomad_pLI

MAINTAINER ShangzhongLi <Shangzhong.Li@pfizer.com>

ENV PATH /opt/miniconda/bin:$PATH
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PERL5LIB=$PERL5LIB:/opt/cpanm/lib/perl5

# install conda
SHELL ["/bin/bash", "-c"]
RUN conda install -y -c bioconda vt && \
     conda install -y -c bioconda bcftools
     
CMD ["/bin/bash"]


     

